version: "3.9"
services:
    webserver:
        build:
            context: .
            dockerfile: Dockerfile
        image: apache
        volumes:
            - .:/otel-webserver-module
        hostname: webserver
        container_name: webserver
        entrypoint: ["bash", "./build.sh"]
