// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/logs/v1/logs.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "opentelemetry/proto/common/v1/common.pb.h"
#include "opentelemetry/proto/resource/v1/resource.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto;
namespace opentelemetry {
namespace proto {
namespace logs {
namespace v1 {
class InstrumentationLibraryLogs;
class InstrumentationLibraryLogsDefaultTypeInternal;
extern InstrumentationLibraryLogsDefaultTypeInternal _InstrumentationLibraryLogs_default_instance_;
class LogRecord;
class LogRecordDefaultTypeInternal;
extern LogRecordDefaultTypeInternal _LogRecord_default_instance_;
class ResourceLogs;
class ResourceLogsDefaultTypeInternal;
extern ResourceLogsDefaultTypeInternal _ResourceLogs_default_instance_;
}  // namespace v1
}  // namespace logs
}  // namespace proto
}  // namespace opentelemetry
PROTOBUF_NAMESPACE_OPEN
template<> ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs* Arena::CreateMaybeMessage<::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs>(Arena*);
template<> ::opentelemetry::proto::logs::v1::LogRecord* Arena::CreateMaybeMessage<::opentelemetry::proto::logs::v1::LogRecord>(Arena*);
template<> ::opentelemetry::proto::logs::v1::ResourceLogs* Arena::CreateMaybeMessage<::opentelemetry::proto::logs::v1::ResourceLogs>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace opentelemetry {
namespace proto {
namespace logs {
namespace v1 {

enum SeverityNumber : int {
  SEVERITY_NUMBER_UNSPECIFIED = 0,
  SEVERITY_NUMBER_TRACE = 1,
  SEVERITY_NUMBER_TRACE2 = 2,
  SEVERITY_NUMBER_TRACE3 = 3,
  SEVERITY_NUMBER_TRACE4 = 4,
  SEVERITY_NUMBER_DEBUG = 5,
  SEVERITY_NUMBER_DEBUG2 = 6,
  SEVERITY_NUMBER_DEBUG3 = 7,
  SEVERITY_NUMBER_DEBUG4 = 8,
  SEVERITY_NUMBER_INFO = 9,
  SEVERITY_NUMBER_INFO2 = 10,
  SEVERITY_NUMBER_INFO3 = 11,
  SEVERITY_NUMBER_INFO4 = 12,
  SEVERITY_NUMBER_WARN = 13,
  SEVERITY_NUMBER_WARN2 = 14,
  SEVERITY_NUMBER_WARN3 = 15,
  SEVERITY_NUMBER_WARN4 = 16,
  SEVERITY_NUMBER_ERROR = 17,
  SEVERITY_NUMBER_ERROR2 = 18,
  SEVERITY_NUMBER_ERROR3 = 19,
  SEVERITY_NUMBER_ERROR4 = 20,
  SEVERITY_NUMBER_FATAL = 21,
  SEVERITY_NUMBER_FATAL2 = 22,
  SEVERITY_NUMBER_FATAL3 = 23,
  SEVERITY_NUMBER_FATAL4 = 24,
  SeverityNumber_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SeverityNumber_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool SeverityNumber_IsValid(int value);
constexpr SeverityNumber SeverityNumber_MIN = SEVERITY_NUMBER_UNSPECIFIED;
constexpr SeverityNumber SeverityNumber_MAX = SEVERITY_NUMBER_FATAL4;
constexpr int SeverityNumber_ARRAYSIZE = SeverityNumber_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SeverityNumber_descriptor();
template<typename T>
inline const std::string& SeverityNumber_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SeverityNumber>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SeverityNumber_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SeverityNumber_descriptor(), enum_t_value);
}
inline bool SeverityNumber_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, SeverityNumber* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SeverityNumber>(
    SeverityNumber_descriptor(), name, value);
}
enum LogRecordFlags : int {
  LOG_RECORD_FLAG_UNSPECIFIED = 0,
  LOG_RECORD_FLAG_TRACE_FLAGS_MASK = 255,
  LogRecordFlags_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  LogRecordFlags_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool LogRecordFlags_IsValid(int value);
constexpr LogRecordFlags LogRecordFlags_MIN = LOG_RECORD_FLAG_UNSPECIFIED;
constexpr LogRecordFlags LogRecordFlags_MAX = LOG_RECORD_FLAG_TRACE_FLAGS_MASK;
constexpr int LogRecordFlags_ARRAYSIZE = LogRecordFlags_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* LogRecordFlags_descriptor();
template<typename T>
inline const std::string& LogRecordFlags_Name(T enum_t_value) {
  static_assert(::std::is_same<T, LogRecordFlags>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function LogRecordFlags_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    LogRecordFlags_descriptor(), enum_t_value);
}
inline bool LogRecordFlags_Parse(
    ::PROTOBUF_NAMESPACE_ID::ConstStringParam name, LogRecordFlags* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<LogRecordFlags>(
    LogRecordFlags_descriptor(), name, value);
}
// ===================================================================

class ResourceLogs PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.logs.v1.ResourceLogs) */ {
 public:
  inline ResourceLogs() : ResourceLogs(nullptr) {}
  virtual ~ResourceLogs();

  ResourceLogs(const ResourceLogs& from);
  ResourceLogs(ResourceLogs&& from) noexcept
    : ResourceLogs() {
    *this = ::std::move(from);
  }

  inline ResourceLogs& operator=(const ResourceLogs& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResourceLogs& operator=(ResourceLogs&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ResourceLogs& default_instance();

  static inline const ResourceLogs* internal_default_instance() {
    return reinterpret_cast<const ResourceLogs*>(
               &_ResourceLogs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResourceLogs& a, ResourceLogs& b) {
    a.Swap(&b);
  }
  inline void Swap(ResourceLogs* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResourceLogs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ResourceLogs* New() const final {
    return CreateMaybeMessage<ResourceLogs>(nullptr);
  }

  ResourceLogs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ResourceLogs>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ResourceLogs& from);
  void MergeFrom(const ResourceLogs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResourceLogs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.logs.v1.ResourceLogs";
  }
  protected:
  explicit ResourceLogs(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInstrumentationLibraryLogsFieldNumber = 2,
    kResourceFieldNumber = 1,
  };
  // repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 2;
  int instrumentation_library_logs_size() const;
  private:
  int _internal_instrumentation_library_logs_size() const;
  public:
  void clear_instrumentation_library_logs();
  ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs* mutable_instrumentation_library_logs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs >*
      mutable_instrumentation_library_logs();
  private:
  const ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs& _internal_instrumentation_library_logs(int index) const;
  ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs* _internal_add_instrumentation_library_logs();
  public:
  const ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs& instrumentation_library_logs(int index) const;
  ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs* add_instrumentation_library_logs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs >&
      instrumentation_library_logs() const;

  // .opentelemetry.proto.resource.v1.Resource resource = 1;
  bool has_resource() const;
  private:
  bool _internal_has_resource() const;
  public:
  void clear_resource();
  const ::opentelemetry::proto::resource::v1::Resource& resource() const;
  ::opentelemetry::proto::resource::v1::Resource* release_resource();
  ::opentelemetry::proto::resource::v1::Resource* mutable_resource();
  void set_allocated_resource(::opentelemetry::proto::resource::v1::Resource* resource);
  private:
  const ::opentelemetry::proto::resource::v1::Resource& _internal_resource() const;
  ::opentelemetry::proto::resource::v1::Resource* _internal_mutable_resource();
  public:
  void unsafe_arena_set_allocated_resource(
      ::opentelemetry::proto::resource::v1::Resource* resource);
  ::opentelemetry::proto::resource::v1::Resource* unsafe_arena_release_resource();

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.logs.v1.ResourceLogs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs > instrumentation_library_logs_;
  ::opentelemetry::proto::resource::v1::Resource* resource_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto;
};
// -------------------------------------------------------------------

class InstrumentationLibraryLogs PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs) */ {
 public:
  inline InstrumentationLibraryLogs() : InstrumentationLibraryLogs(nullptr) {}
  virtual ~InstrumentationLibraryLogs();

  InstrumentationLibraryLogs(const InstrumentationLibraryLogs& from);
  InstrumentationLibraryLogs(InstrumentationLibraryLogs&& from) noexcept
    : InstrumentationLibraryLogs() {
    *this = ::std::move(from);
  }

  inline InstrumentationLibraryLogs& operator=(const InstrumentationLibraryLogs& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstrumentationLibraryLogs& operator=(InstrumentationLibraryLogs&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const InstrumentationLibraryLogs& default_instance();

  static inline const InstrumentationLibraryLogs* internal_default_instance() {
    return reinterpret_cast<const InstrumentationLibraryLogs*>(
               &_InstrumentationLibraryLogs_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(InstrumentationLibraryLogs& a, InstrumentationLibraryLogs& b) {
    a.Swap(&b);
  }
  inline void Swap(InstrumentationLibraryLogs* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstrumentationLibraryLogs* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline InstrumentationLibraryLogs* New() const final {
    return CreateMaybeMessage<InstrumentationLibraryLogs>(nullptr);
  }

  InstrumentationLibraryLogs* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<InstrumentationLibraryLogs>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const InstrumentationLibraryLogs& from);
  void MergeFrom(const InstrumentationLibraryLogs& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstrumentationLibraryLogs* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.logs.v1.InstrumentationLibraryLogs";
  }
  protected:
  explicit InstrumentationLibraryLogs(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLogsFieldNumber = 2,
    kInstrumentationLibraryFieldNumber = 1,
  };
  // repeated .opentelemetry.proto.logs.v1.LogRecord logs = 2;
  int logs_size() const;
  private:
  int _internal_logs_size() const;
  public:
  void clear_logs();
  ::opentelemetry::proto::logs::v1::LogRecord* mutable_logs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::LogRecord >*
      mutable_logs();
  private:
  const ::opentelemetry::proto::logs::v1::LogRecord& _internal_logs(int index) const;
  ::opentelemetry::proto::logs::v1::LogRecord* _internal_add_logs();
  public:
  const ::opentelemetry::proto::logs::v1::LogRecord& logs(int index) const;
  ::opentelemetry::proto::logs::v1::LogRecord* add_logs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::LogRecord >&
      logs() const;

  // .opentelemetry.proto.common.v1.InstrumentationLibrary instrumentation_library = 1;
  bool has_instrumentation_library() const;
  private:
  bool _internal_has_instrumentation_library() const;
  public:
  void clear_instrumentation_library();
  const ::opentelemetry::proto::common::v1::InstrumentationLibrary& instrumentation_library() const;
  ::opentelemetry::proto::common::v1::InstrumentationLibrary* release_instrumentation_library();
  ::opentelemetry::proto::common::v1::InstrumentationLibrary* mutable_instrumentation_library();
  void set_allocated_instrumentation_library(::opentelemetry::proto::common::v1::InstrumentationLibrary* instrumentation_library);
  private:
  const ::opentelemetry::proto::common::v1::InstrumentationLibrary& _internal_instrumentation_library() const;
  ::opentelemetry::proto::common::v1::InstrumentationLibrary* _internal_mutable_instrumentation_library();
  public:
  void unsafe_arena_set_allocated_instrumentation_library(
      ::opentelemetry::proto::common::v1::InstrumentationLibrary* instrumentation_library);
  ::opentelemetry::proto::common::v1::InstrumentationLibrary* unsafe_arena_release_instrumentation_library();

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::LogRecord > logs_;
  ::opentelemetry::proto::common::v1::InstrumentationLibrary* instrumentation_library_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto;
};
// -------------------------------------------------------------------

class LogRecord PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:opentelemetry.proto.logs.v1.LogRecord) */ {
 public:
  inline LogRecord() : LogRecord(nullptr) {}
  virtual ~LogRecord();

  LogRecord(const LogRecord& from);
  LogRecord(LogRecord&& from) noexcept
    : LogRecord() {
    *this = ::std::move(from);
  }

  inline LogRecord& operator=(const LogRecord& from) {
    CopyFrom(from);
    return *this;
  }
  inline LogRecord& operator=(LogRecord&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const LogRecord& default_instance();

  static inline const LogRecord* internal_default_instance() {
    return reinterpret_cast<const LogRecord*>(
               &_LogRecord_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(LogRecord& a, LogRecord& b) {
    a.Swap(&b);
  }
  inline void Swap(LogRecord* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LogRecord* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline LogRecord* New() const final {
    return CreateMaybeMessage<LogRecord>(nullptr);
  }

  LogRecord* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<LogRecord>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const LogRecord& from);
  void MergeFrom(const LogRecord& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(LogRecord* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "opentelemetry.proto.logs.v1.LogRecord";
  }
  protected:
  explicit LogRecord(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto);
    return ::descriptor_table_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAttributesFieldNumber = 6,
    kSeverityTextFieldNumber = 3,
    kNameFieldNumber = 4,
    kTraceIdFieldNumber = 9,
    kSpanIdFieldNumber = 10,
    kBodyFieldNumber = 5,
    kTimeUnixNanoFieldNumber = 1,
    kSeverityNumberFieldNumber = 2,
    kDroppedAttributesCountFieldNumber = 7,
    kFlagsFieldNumber = 8,
  };
  // repeated .opentelemetry.proto.common.v1.KeyValue attributes = 6;
  int attributes_size() const;
  private:
  int _internal_attributes_size() const;
  public:
  void clear_attributes();
  ::opentelemetry::proto::common::v1::KeyValue* mutable_attributes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >*
      mutable_attributes();
  private:
  const ::opentelemetry::proto::common::v1::KeyValue& _internal_attributes(int index) const;
  ::opentelemetry::proto::common::v1::KeyValue* _internal_add_attributes();
  public:
  const ::opentelemetry::proto::common::v1::KeyValue& attributes(int index) const;
  ::opentelemetry::proto::common::v1::KeyValue* add_attributes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >&
      attributes() const;

  // string severity_text = 3;
  void clear_severity_text();
  const std::string& severity_text() const;
  void set_severity_text(const std::string& value);
  void set_severity_text(std::string&& value);
  void set_severity_text(const char* value);
  void set_severity_text(const char* value, size_t size);
  std::string* mutable_severity_text();
  std::string* release_severity_text();
  void set_allocated_severity_text(std::string* severity_text);
  private:
  const std::string& _internal_severity_text() const;
  void _internal_set_severity_text(const std::string& value);
  std::string* _internal_mutable_severity_text();
  public:

  // string name = 4;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // bytes trace_id = 9;
  void clear_trace_id();
  const std::string& trace_id() const;
  void set_trace_id(const std::string& value);
  void set_trace_id(std::string&& value);
  void set_trace_id(const char* value);
  void set_trace_id(const void* value, size_t size);
  std::string* mutable_trace_id();
  std::string* release_trace_id();
  void set_allocated_trace_id(std::string* trace_id);
  private:
  const std::string& _internal_trace_id() const;
  void _internal_set_trace_id(const std::string& value);
  std::string* _internal_mutable_trace_id();
  public:

  // bytes span_id = 10;
  void clear_span_id();
  const std::string& span_id() const;
  void set_span_id(const std::string& value);
  void set_span_id(std::string&& value);
  void set_span_id(const char* value);
  void set_span_id(const void* value, size_t size);
  std::string* mutable_span_id();
  std::string* release_span_id();
  void set_allocated_span_id(std::string* span_id);
  private:
  const std::string& _internal_span_id() const;
  void _internal_set_span_id(const std::string& value);
  std::string* _internal_mutable_span_id();
  public:

  // .opentelemetry.proto.common.v1.AnyValue body = 5;
  bool has_body() const;
  private:
  bool _internal_has_body() const;
  public:
  void clear_body();
  const ::opentelemetry::proto::common::v1::AnyValue& body() const;
  ::opentelemetry::proto::common::v1::AnyValue* release_body();
  ::opentelemetry::proto::common::v1::AnyValue* mutable_body();
  void set_allocated_body(::opentelemetry::proto::common::v1::AnyValue* body);
  private:
  const ::opentelemetry::proto::common::v1::AnyValue& _internal_body() const;
  ::opentelemetry::proto::common::v1::AnyValue* _internal_mutable_body();
  public:
  void unsafe_arena_set_allocated_body(
      ::opentelemetry::proto::common::v1::AnyValue* body);
  ::opentelemetry::proto::common::v1::AnyValue* unsafe_arena_release_body();

  // fixed64 time_unix_nano = 1;
  void clear_time_unix_nano();
  ::PROTOBUF_NAMESPACE_ID::uint64 time_unix_nano() const;
  void set_time_unix_nano(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_time_unix_nano() const;
  void _internal_set_time_unix_nano(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .opentelemetry.proto.logs.v1.SeverityNumber severity_number = 2;
  void clear_severity_number();
  ::opentelemetry::proto::logs::v1::SeverityNumber severity_number() const;
  void set_severity_number(::opentelemetry::proto::logs::v1::SeverityNumber value);
  private:
  ::opentelemetry::proto::logs::v1::SeverityNumber _internal_severity_number() const;
  void _internal_set_severity_number(::opentelemetry::proto::logs::v1::SeverityNumber value);
  public:

  // uint32 dropped_attributes_count = 7;
  void clear_dropped_attributes_count();
  ::PROTOBUF_NAMESPACE_ID::uint32 dropped_attributes_count() const;
  void set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_dropped_attributes_count() const;
  void _internal_set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // fixed32 flags = 8;
  void clear_flags();
  ::PROTOBUF_NAMESPACE_ID::uint32 flags() const;
  void set_flags(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_flags() const;
  void _internal_set_flags(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:opentelemetry.proto.logs.v1.LogRecord)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue > attributes_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr severity_text_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr trace_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr span_id_;
  ::opentelemetry::proto::common::v1::AnyValue* body_;
  ::PROTOBUF_NAMESPACE_ID::uint64 time_unix_nano_;
  int severity_number_;
  ::PROTOBUF_NAMESPACE_ID::uint32 dropped_attributes_count_;
  ::PROTOBUF_NAMESPACE_ID::uint32 flags_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResourceLogs

// .opentelemetry.proto.resource.v1.Resource resource = 1;
inline bool ResourceLogs::_internal_has_resource() const {
  return this != internal_default_instance() && resource_ != nullptr;
}
inline bool ResourceLogs::has_resource() const {
  return _internal_has_resource();
}
inline const ::opentelemetry::proto::resource::v1::Resource& ResourceLogs::_internal_resource() const {
  const ::opentelemetry::proto::resource::v1::Resource* p = resource_;
  return p != nullptr ? *p : reinterpret_cast<const ::opentelemetry::proto::resource::v1::Resource&>(
      ::opentelemetry::proto::resource::v1::_Resource_default_instance_);
}
inline const ::opentelemetry::proto::resource::v1::Resource& ResourceLogs::resource() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.ResourceLogs.resource)
  return _internal_resource();
}
inline void ResourceLogs::unsafe_arena_set_allocated_resource(
    ::opentelemetry::proto::resource::v1::Resource* resource) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(resource_);
  }
  resource_ = resource;
  if (resource) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.logs.v1.ResourceLogs.resource)
}
inline ::opentelemetry::proto::resource::v1::Resource* ResourceLogs::release_resource() {
  
  ::opentelemetry::proto::resource::v1::Resource* temp = resource_;
  resource_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::opentelemetry::proto::resource::v1::Resource* ResourceLogs::unsafe_arena_release_resource() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.logs.v1.ResourceLogs.resource)
  
  ::opentelemetry::proto::resource::v1::Resource* temp = resource_;
  resource_ = nullptr;
  return temp;
}
inline ::opentelemetry::proto::resource::v1::Resource* ResourceLogs::_internal_mutable_resource() {
  
  if (resource_ == nullptr) {
    auto* p = CreateMaybeMessage<::opentelemetry::proto::resource::v1::Resource>(GetArena());
    resource_ = p;
  }
  return resource_;
}
inline ::opentelemetry::proto::resource::v1::Resource* ResourceLogs::mutable_resource() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.ResourceLogs.resource)
  return _internal_mutable_resource();
}
inline void ResourceLogs::set_allocated_resource(::opentelemetry::proto::resource::v1::Resource* resource) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(resource_);
  }
  if (resource) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(resource)->GetArena();
    if (message_arena != submessage_arena) {
      resource = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, resource, submessage_arena);
    }
    
  } else {
    
  }
  resource_ = resource;
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.logs.v1.ResourceLogs.resource)
}

// repeated .opentelemetry.proto.logs.v1.InstrumentationLibraryLogs instrumentation_library_logs = 2;
inline int ResourceLogs::_internal_instrumentation_library_logs_size() const {
  return instrumentation_library_logs_.size();
}
inline int ResourceLogs::instrumentation_library_logs_size() const {
  return _internal_instrumentation_library_logs_size();
}
inline void ResourceLogs::clear_instrumentation_library_logs() {
  instrumentation_library_logs_.Clear();
}
inline ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs* ResourceLogs::mutable_instrumentation_library_logs(int index) {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.ResourceLogs.instrumentation_library_logs)
  return instrumentation_library_logs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs >*
ResourceLogs::mutable_instrumentation_library_logs() {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.logs.v1.ResourceLogs.instrumentation_library_logs)
  return &instrumentation_library_logs_;
}
inline const ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs& ResourceLogs::_internal_instrumentation_library_logs(int index) const {
  return instrumentation_library_logs_.Get(index);
}
inline const ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs& ResourceLogs::instrumentation_library_logs(int index) const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.ResourceLogs.instrumentation_library_logs)
  return _internal_instrumentation_library_logs(index);
}
inline ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs* ResourceLogs::_internal_add_instrumentation_library_logs() {
  return instrumentation_library_logs_.Add();
}
inline ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs* ResourceLogs::add_instrumentation_library_logs() {
  // @@protoc_insertion_point(field_add:opentelemetry.proto.logs.v1.ResourceLogs.instrumentation_library_logs)
  return _internal_add_instrumentation_library_logs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::InstrumentationLibraryLogs >&
ResourceLogs::instrumentation_library_logs() const {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.logs.v1.ResourceLogs.instrumentation_library_logs)
  return instrumentation_library_logs_;
}

// -------------------------------------------------------------------

// InstrumentationLibraryLogs

// .opentelemetry.proto.common.v1.InstrumentationLibrary instrumentation_library = 1;
inline bool InstrumentationLibraryLogs::_internal_has_instrumentation_library() const {
  return this != internal_default_instance() && instrumentation_library_ != nullptr;
}
inline bool InstrumentationLibraryLogs::has_instrumentation_library() const {
  return _internal_has_instrumentation_library();
}
inline const ::opentelemetry::proto::common::v1::InstrumentationLibrary& InstrumentationLibraryLogs::_internal_instrumentation_library() const {
  const ::opentelemetry::proto::common::v1::InstrumentationLibrary* p = instrumentation_library_;
  return p != nullptr ? *p : reinterpret_cast<const ::opentelemetry::proto::common::v1::InstrumentationLibrary&>(
      ::opentelemetry::proto::common::v1::_InstrumentationLibrary_default_instance_);
}
inline const ::opentelemetry::proto::common::v1::InstrumentationLibrary& InstrumentationLibraryLogs::instrumentation_library() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.instrumentation_library)
  return _internal_instrumentation_library();
}
inline void InstrumentationLibraryLogs::unsafe_arena_set_allocated_instrumentation_library(
    ::opentelemetry::proto::common::v1::InstrumentationLibrary* instrumentation_library) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(instrumentation_library_);
  }
  instrumentation_library_ = instrumentation_library;
  if (instrumentation_library) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.instrumentation_library)
}
inline ::opentelemetry::proto::common::v1::InstrumentationLibrary* InstrumentationLibraryLogs::release_instrumentation_library() {
  
  ::opentelemetry::proto::common::v1::InstrumentationLibrary* temp = instrumentation_library_;
  instrumentation_library_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::opentelemetry::proto::common::v1::InstrumentationLibrary* InstrumentationLibraryLogs::unsafe_arena_release_instrumentation_library() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.instrumentation_library)
  
  ::opentelemetry::proto::common::v1::InstrumentationLibrary* temp = instrumentation_library_;
  instrumentation_library_ = nullptr;
  return temp;
}
inline ::opentelemetry::proto::common::v1::InstrumentationLibrary* InstrumentationLibraryLogs::_internal_mutable_instrumentation_library() {
  
  if (instrumentation_library_ == nullptr) {
    auto* p = CreateMaybeMessage<::opentelemetry::proto::common::v1::InstrumentationLibrary>(GetArena());
    instrumentation_library_ = p;
  }
  return instrumentation_library_;
}
inline ::opentelemetry::proto::common::v1::InstrumentationLibrary* InstrumentationLibraryLogs::mutable_instrumentation_library() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.instrumentation_library)
  return _internal_mutable_instrumentation_library();
}
inline void InstrumentationLibraryLogs::set_allocated_instrumentation_library(::opentelemetry::proto::common::v1::InstrumentationLibrary* instrumentation_library) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(instrumentation_library_);
  }
  if (instrumentation_library) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(instrumentation_library)->GetArena();
    if (message_arena != submessage_arena) {
      instrumentation_library = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, instrumentation_library, submessage_arena);
    }
    
  } else {
    
  }
  instrumentation_library_ = instrumentation_library;
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.instrumentation_library)
}

// repeated .opentelemetry.proto.logs.v1.LogRecord logs = 2;
inline int InstrumentationLibraryLogs::_internal_logs_size() const {
  return logs_.size();
}
inline int InstrumentationLibraryLogs::logs_size() const {
  return _internal_logs_size();
}
inline void InstrumentationLibraryLogs::clear_logs() {
  logs_.Clear();
}
inline ::opentelemetry::proto::logs::v1::LogRecord* InstrumentationLibraryLogs::mutable_logs(int index) {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.logs)
  return logs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::LogRecord >*
InstrumentationLibraryLogs::mutable_logs() {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.logs)
  return &logs_;
}
inline const ::opentelemetry::proto::logs::v1::LogRecord& InstrumentationLibraryLogs::_internal_logs(int index) const {
  return logs_.Get(index);
}
inline const ::opentelemetry::proto::logs::v1::LogRecord& InstrumentationLibraryLogs::logs(int index) const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.logs)
  return _internal_logs(index);
}
inline ::opentelemetry::proto::logs::v1::LogRecord* InstrumentationLibraryLogs::_internal_add_logs() {
  return logs_.Add();
}
inline ::opentelemetry::proto::logs::v1::LogRecord* InstrumentationLibraryLogs::add_logs() {
  // @@protoc_insertion_point(field_add:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.logs)
  return _internal_add_logs();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::logs::v1::LogRecord >&
InstrumentationLibraryLogs::logs() const {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.logs.v1.InstrumentationLibraryLogs.logs)
  return logs_;
}

// -------------------------------------------------------------------

// LogRecord

// fixed64 time_unix_nano = 1;
inline void LogRecord::clear_time_unix_nano() {
  time_unix_nano_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LogRecord::_internal_time_unix_nano() const {
  return time_unix_nano_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 LogRecord::time_unix_nano() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.time_unix_nano)
  return _internal_time_unix_nano();
}
inline void LogRecord::_internal_set_time_unix_nano(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  time_unix_nano_ = value;
}
inline void LogRecord::set_time_unix_nano(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_time_unix_nano(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.time_unix_nano)
}

// .opentelemetry.proto.logs.v1.SeverityNumber severity_number = 2;
inline void LogRecord::clear_severity_number() {
  severity_number_ = 0;
}
inline ::opentelemetry::proto::logs::v1::SeverityNumber LogRecord::_internal_severity_number() const {
  return static_cast< ::opentelemetry::proto::logs::v1::SeverityNumber >(severity_number_);
}
inline ::opentelemetry::proto::logs::v1::SeverityNumber LogRecord::severity_number() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.severity_number)
  return _internal_severity_number();
}
inline void LogRecord::_internal_set_severity_number(::opentelemetry::proto::logs::v1::SeverityNumber value) {
  
  severity_number_ = value;
}
inline void LogRecord::set_severity_number(::opentelemetry::proto::logs::v1::SeverityNumber value) {
  _internal_set_severity_number(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.severity_number)
}

// string severity_text = 3;
inline void LogRecord::clear_severity_text() {
  severity_text_.ClearToEmpty();
}
inline const std::string& LogRecord::severity_text() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.severity_text)
  return _internal_severity_text();
}
inline void LogRecord::set_severity_text(const std::string& value) {
  _internal_set_severity_text(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.severity_text)
}
inline std::string* LogRecord::mutable_severity_text() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.LogRecord.severity_text)
  return _internal_mutable_severity_text();
}
inline const std::string& LogRecord::_internal_severity_text() const {
  return severity_text_.Get();
}
inline void LogRecord::_internal_set_severity_text(const std::string& value) {
  
  severity_text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void LogRecord::set_severity_text(std::string&& value) {
  
  severity_text_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.logs.v1.LogRecord.severity_text)
}
inline void LogRecord::set_severity_text(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  severity_text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.logs.v1.LogRecord.severity_text)
}
inline void LogRecord::set_severity_text(const char* value,
    size_t size) {
  
  severity_text_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.logs.v1.LogRecord.severity_text)
}
inline std::string* LogRecord::_internal_mutable_severity_text() {
  
  return severity_text_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* LogRecord::release_severity_text() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.logs.v1.LogRecord.severity_text)
  return severity_text_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogRecord::set_allocated_severity_text(std::string* severity_text) {
  if (severity_text != nullptr) {
    
  } else {
    
  }
  severity_text_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), severity_text,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.logs.v1.LogRecord.severity_text)
}

// string name = 4;
inline void LogRecord::clear_name() {
  name_.ClearToEmpty();
}
inline const std::string& LogRecord::name() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.name)
  return _internal_name();
}
inline void LogRecord::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.name)
}
inline std::string* LogRecord::mutable_name() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.LogRecord.name)
  return _internal_mutable_name();
}
inline const std::string& LogRecord::_internal_name() const {
  return name_.Get();
}
inline void LogRecord::_internal_set_name(const std::string& value) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void LogRecord::set_name(std::string&& value) {
  
  name_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.logs.v1.LogRecord.name)
}
inline void LogRecord::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.logs.v1.LogRecord.name)
}
inline void LogRecord::set_name(const char* value,
    size_t size) {
  
  name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.logs.v1.LogRecord.name)
}
inline std::string* LogRecord::_internal_mutable_name() {
  
  return name_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* LogRecord::release_name() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.logs.v1.LogRecord.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogRecord::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.logs.v1.LogRecord.name)
}

// .opentelemetry.proto.common.v1.AnyValue body = 5;
inline bool LogRecord::_internal_has_body() const {
  return this != internal_default_instance() && body_ != nullptr;
}
inline bool LogRecord::has_body() const {
  return _internal_has_body();
}
inline const ::opentelemetry::proto::common::v1::AnyValue& LogRecord::_internal_body() const {
  const ::opentelemetry::proto::common::v1::AnyValue* p = body_;
  return p != nullptr ? *p : reinterpret_cast<const ::opentelemetry::proto::common::v1::AnyValue&>(
      ::opentelemetry::proto::common::v1::_AnyValue_default_instance_);
}
inline const ::opentelemetry::proto::common::v1::AnyValue& LogRecord::body() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.body)
  return _internal_body();
}
inline void LogRecord::unsafe_arena_set_allocated_body(
    ::opentelemetry::proto::common::v1::AnyValue* body) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  body_ = body;
  if (body) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.logs.v1.LogRecord.body)
}
inline ::opentelemetry::proto::common::v1::AnyValue* LogRecord::release_body() {
  
  ::opentelemetry::proto::common::v1::AnyValue* temp = body_;
  body_ = nullptr;
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::opentelemetry::proto::common::v1::AnyValue* LogRecord::unsafe_arena_release_body() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.logs.v1.LogRecord.body)
  
  ::opentelemetry::proto::common::v1::AnyValue* temp = body_;
  body_ = nullptr;
  return temp;
}
inline ::opentelemetry::proto::common::v1::AnyValue* LogRecord::_internal_mutable_body() {
  
  if (body_ == nullptr) {
    auto* p = CreateMaybeMessage<::opentelemetry::proto::common::v1::AnyValue>(GetArena());
    body_ = p;
  }
  return body_;
}
inline ::opentelemetry::proto::common::v1::AnyValue* LogRecord::mutable_body() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.LogRecord.body)
  return _internal_mutable_body();
}
inline void LogRecord::set_allocated_body(::opentelemetry::proto::common::v1::AnyValue* body) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(body_);
  }
  if (body) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(body)->GetArena();
    if (message_arena != submessage_arena) {
      body = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, body, submessage_arena);
    }
    
  } else {
    
  }
  body_ = body;
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.logs.v1.LogRecord.body)
}

// repeated .opentelemetry.proto.common.v1.KeyValue attributes = 6;
inline int LogRecord::_internal_attributes_size() const {
  return attributes_.size();
}
inline int LogRecord::attributes_size() const {
  return _internal_attributes_size();
}
inline ::opentelemetry::proto::common::v1::KeyValue* LogRecord::mutable_attributes(int index) {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.LogRecord.attributes)
  return attributes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >*
LogRecord::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.logs.v1.LogRecord.attributes)
  return &attributes_;
}
inline const ::opentelemetry::proto::common::v1::KeyValue& LogRecord::_internal_attributes(int index) const {
  return attributes_.Get(index);
}
inline const ::opentelemetry::proto::common::v1::KeyValue& LogRecord::attributes(int index) const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.attributes)
  return _internal_attributes(index);
}
inline ::opentelemetry::proto::common::v1::KeyValue* LogRecord::_internal_add_attributes() {
  return attributes_.Add();
}
inline ::opentelemetry::proto::common::v1::KeyValue* LogRecord::add_attributes() {
  // @@protoc_insertion_point(field_add:opentelemetry.proto.logs.v1.LogRecord.attributes)
  return _internal_add_attributes();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::opentelemetry::proto::common::v1::KeyValue >&
LogRecord::attributes() const {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.logs.v1.LogRecord.attributes)
  return attributes_;
}

// uint32 dropped_attributes_count = 7;
inline void LogRecord::clear_dropped_attributes_count() {
  dropped_attributes_count_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LogRecord::_internal_dropped_attributes_count() const {
  return dropped_attributes_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LogRecord::dropped_attributes_count() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.dropped_attributes_count)
  return _internal_dropped_attributes_count();
}
inline void LogRecord::_internal_set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  dropped_attributes_count_ = value;
}
inline void LogRecord::set_dropped_attributes_count(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_dropped_attributes_count(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.dropped_attributes_count)
}

// fixed32 flags = 8;
inline void LogRecord::clear_flags() {
  flags_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LogRecord::_internal_flags() const {
  return flags_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 LogRecord::flags() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.flags)
  return _internal_flags();
}
inline void LogRecord::_internal_set_flags(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  flags_ = value;
}
inline void LogRecord::set_flags(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_flags(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.flags)
}

// bytes trace_id = 9;
inline void LogRecord::clear_trace_id() {
  trace_id_.ClearToEmpty();
}
inline const std::string& LogRecord::trace_id() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.trace_id)
  return _internal_trace_id();
}
inline void LogRecord::set_trace_id(const std::string& value) {
  _internal_set_trace_id(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.trace_id)
}
inline std::string* LogRecord::mutable_trace_id() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.LogRecord.trace_id)
  return _internal_mutable_trace_id();
}
inline const std::string& LogRecord::_internal_trace_id() const {
  return trace_id_.Get();
}
inline void LogRecord::_internal_set_trace_id(const std::string& value) {
  
  trace_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void LogRecord::set_trace_id(std::string&& value) {
  
  trace_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.logs.v1.LogRecord.trace_id)
}
inline void LogRecord::set_trace_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  trace_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.logs.v1.LogRecord.trace_id)
}
inline void LogRecord::set_trace_id(const void* value,
    size_t size) {
  
  trace_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.logs.v1.LogRecord.trace_id)
}
inline std::string* LogRecord::_internal_mutable_trace_id() {
  
  return trace_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* LogRecord::release_trace_id() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.logs.v1.LogRecord.trace_id)
  return trace_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogRecord::set_allocated_trace_id(std::string* trace_id) {
  if (trace_id != nullptr) {
    
  } else {
    
  }
  trace_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), trace_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.logs.v1.LogRecord.trace_id)
}

// bytes span_id = 10;
inline void LogRecord::clear_span_id() {
  span_id_.ClearToEmpty();
}
inline const std::string& LogRecord::span_id() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.logs.v1.LogRecord.span_id)
  return _internal_span_id();
}
inline void LogRecord::set_span_id(const std::string& value) {
  _internal_set_span_id(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.logs.v1.LogRecord.span_id)
}
inline std::string* LogRecord::mutable_span_id() {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.logs.v1.LogRecord.span_id)
  return _internal_mutable_span_id();
}
inline const std::string& LogRecord::_internal_span_id() const {
  return span_id_.Get();
}
inline void LogRecord::_internal_set_span_id(const std::string& value) {
  
  span_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void LogRecord::set_span_id(std::string&& value) {
  
  span_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:opentelemetry.proto.logs.v1.LogRecord.span_id)
}
inline void LogRecord::set_span_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  span_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:opentelemetry.proto.logs.v1.LogRecord.span_id)
}
inline void LogRecord::set_span_id(const void* value,
    size_t size) {
  
  span_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:opentelemetry.proto.logs.v1.LogRecord.span_id)
}
inline std::string* LogRecord::_internal_mutable_span_id() {
  
  return span_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* LogRecord::release_span_id() {
  // @@protoc_insertion_point(field_release:opentelemetry.proto.logs.v1.LogRecord.span_id)
  return span_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void LogRecord::set_allocated_span_id(std::string* span_id) {
  if (span_id != nullptr) {
    
  } else {
    
  }
  span_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), span_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.logs.v1.LogRecord.span_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace v1
}  // namespace logs
}  // namespace proto
}  // namespace opentelemetry

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::opentelemetry::proto::logs::v1::SeverityNumber> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::opentelemetry::proto::logs::v1::SeverityNumber>() {
  return ::opentelemetry::proto::logs::v1::SeverityNumber_descriptor();
}
template <> struct is_proto_enum< ::opentelemetry::proto::logs::v1::LogRecordFlags> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::opentelemetry::proto::logs::v1::LogRecordFlags>() {
  return ::opentelemetry::proto::logs::v1::LogRecordFlags_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2flogs_2fv1_2flogs_2eproto
